server {
    listen 80;
    index index.php;
    root /var/www/public;

    access_log /dev/stdout;
    error_log  /dev/stderr;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        # php-fpm runs in the same container
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
